In [4]:
from datetime import date
import pandas as pd
import sys
from pathlib import Path
import numpy as np

In [8]:
df = pd.read_csv("../test_data/natural-disasters.csv")

In [9]:
df

,Number of deaths from drought,Number of people injured from drought,Number of people affected from drought,Number of people left homeless from drought,Number of total people affected by drought,Reconstruction costs from drought,Insured damages against drought,Total economic damages from drought,Death rates from drought,Injury rates from drought,...,Total economic damages from landslides as a share of GDP,Total economic damages from mass movements as a share of GDP,Total economic damages from storms as a share of GDP,Total economic damages from volcanic activity as a share of GDP,Total economic damages from volcanic activity as a share of GDP.1,Entity,Year,deaths_rate_per_100k_storm,injured_rate_per_100k_storm,total_affected_rate_per_100k_all_disasters
0,0.0,0.0,0.0,0,0.0,NaN,NaN,NaN,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,Afghanistan,1950,0.000000,0.000000,2.381236
1,0.0,0.0,4800.0,0,4800.0,0.0,0.0,20.0,0.0,0.0,...,0.0,0.0,0.000000,0.0,0.0,Afghanistan,1960,0.000000,0.000000,44.060951
2,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.000000,0.0,0.0,Afghanistan,1970,0.000000,0.000000,547.029875
3,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.000000,0.0,0.0,Afghanistan,1980,0.000000,0.000000,218.081859
4,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.000000,0.0,0.0,Afghanistan,1990,0.006322,0.000000,316.150814
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1599,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.000000,0.0,0.0,Zimbabwe,1970,0.017477,0.000000,0.000000
1600,0.0,0.0,0.0,0,0.0,0.0,0.0,100.0,0.0,0.0,...,0.0,0.0,0.000000,0.0,0.0,Zimbabwe,1980,0.000000,0.000000,0.000000
1601,0.0,0.0,505500.0,0,505500.0,0.0,0.0,5000.0,0.0,0.0,...,0.0,0.0,0.000000,0.0,0.0,Zimbabwe,1990,0.000000,0.000000,4839.765250
1602,0.0,0.0,810000.0,0,810000.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.002268,0.0,0.0,Zimbabwe,2000,0.006677,0.000000,7023.254487
1603,0.0,0.0,1286761.8,0,1286761.8,0.0,0.0,50000.0,0.0,0.0,...,0.0,0.0,0.099393,0.0,0.0,Zimbabwe,2010,0.634451,0.216912,9656.191875

In [14]:
df.isnull().sum().sum()

34912

In [18]:
null_df = df.isnull()

In [ ]:
null_df